language: python
python:
  - 2.7
  - pypy
  - 3.3
  - 3.4
  - 3.5
  - nightly
  - pypy3

services:
  - redis-server
  - mysql

env:
  - TRAVIS_NODE_VERSION="6"

install:
  - virtualenv nodeps
  - ./nodeps/bin/python setup.py install
  - . ./nodeps/bin/activate
  - python setup.py install
  - pip install python-coveralls
  - pip install nose
  - pip install selenium
  - pip freeze

  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install -g minifier@0.8.0
  - npm install -g phantomjs-prebuilt

addons:
  apt:
    packages:
      - nginx

before_script:
  - sudo apt-get install -y -qq postfix
  - sudo service postfix start

  - sudo cp ./travis/conf/nginx.conf /etc/nginx/nginx.conf
  - sudo cat /etc/nginx/nginx.conf
  
  - sudo /etc/init.d/nginx restart
  - sudo ps -ef | grep nginx

  - node --version
  - which minify

  - mysql -e "DROP DATABASE IF EXISTS dp_test_db;" -u root
  - mysql -e "CREATE DATABASE IF NOT EXISTS dp_test_db;" -u root

script: ./nodeps/bin/nosetests -w ./tests

after_success:
  - coveralls