language: python
python:
  - 2.7
  - pypy
  - 3.3
  - 3.4
  - 3.5
  - nightly
  - pypy3

services:
  - redis-server
  - mysql

install:
  - virtualenv nodeps
  - ./nodeps/bin/python setup.py install
  - . ./nodeps/bin/activate
  - python setup.py install
  - pip install python-coveralls
  - pip install nose
  - pip install CyMySQL==0.8.9
  - pip freeze

addons:
  apt:
    packages:
      - nginx

before_script:
  - sudo cp ./travis/conf/nginx.conf /etc/nginx/nginx.conf
  - sudo cat /etc/nginx/nginx.conf
  
  - sudo /etc/init.d/nginx restart
  - sudo ps -ef | grep nginx

  - mysql -e "DROP DATABASE IF EXISTS dp_test_db;" -u root
  - mysql -e "CREATE DATABASE IF NOT EXISTS dp_test_db;" -u root

script: ./nodeps/bin/nosetests -w ./tests

after_success:
  - coveralls