language: python
python:
  - 2.7
  - pypy
  - 3.3
  - 3.4
  - 3.5
  - nightly
  - pypy3

install:
  - virtualenv nodeps
  - ./nodeps/bin/python setup.py install
  - ./nodeps/bin/activate
  - python setup.py install
  - pip freeze

script: nosetests