language: python
python:
  - 2.7
  - pypy
  - 3.3
  - 3.4
  - 3.5
  - nightly
  - pypy3

services:
  - redis-server
  - mysql

install:
  - virtualenv nodeps
  - ./nodeps/bin/python setup.py install
  - . ./nodeps/bin/activate
  - python setup.py install
  - pip install python-coveralls
  - pip install nose
  - pip freeze

before_script:
  - mysql -e "DROP DATABASE IF EXISTS dp_test_db;" -u root
  - mysql -e "CREATE DATABASE IF NOT EXISTS dp_test_db;" -u root

script: ./nodeps/bin/nosetests -w ./tests

after_success:
  - coveralls